// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmw9vz5n8BWIbhMxWvOTWAn65nyA3_cBI',
    appId: '1:564498907475:web:878f537a19b21ac083e1a6',
    messagingSenderId: '564498907475',
    projectId: 'finance-app-734e6',
    authDomain: 'finance-app-734e6.firebaseapp.com',
    storageBucket: 'finance-app-734e6.firebasestorage.app',
    measurementId: 'G-L7KNGW671M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7S56tXskCxTQ2v_G7rR_MhUEbQY_DRI',
    appId: '1:564498907475:android:d83fc43ad69740c083e1a6',
    messagingSenderId: '564498907475',
    projectId: 'finance-app-734e6',
    storageBucket: 'finance-app-734e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJA2ykIExGPieMhgjNsXoQ6MEcdjIu7Nw',
    appId: '1:564498907475:ios:f11861703a88079f83e1a6',
    messagingSenderId: '564498907475',
    projectId: 'finance-app-734e6',
    storageBucket: 'finance-app-734e6.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJA2ykIExGPieMhgjNsXoQ6MEcdjIu7Nw',
    appId: '1:564498907475:ios:f11861703a88079f83e1a6',
    messagingSenderId: '564498907475',
    projectId: 'finance-app-734e6',
    storageBucket: 'finance-app-734e6.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmw9vz5n8BWIbhMxWvOTWAn65nyA3_cBI',
    appId: '1:564498907475:web:fac91212abd8f8aa83e1a6',
    messagingSenderId: '564498907475',
    projectId: 'finance-app-734e6',
    authDomain: 'finance-app-734e6.firebaseapp.com',
    storageBucket: 'finance-app-734e6.firebasestorage.app',
    measurementId: 'G-CS971T236Q',
  );
}
